spring:
  application:
    name: enotes_api_service
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Anurag@12

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: anuragkatare1999@gmail.com
    password: suiw bqek cwjw tubl
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans,loggers
  endpoint:
    shutdown:
      enabled: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

file:
  upload:
    path: notes/
